version: '2'
services:
  php-cli:
    build:
      context: './../'
      dockerfile: ./docker/Dockerfile
      args:
        - INSTALL_ZIP=true
        - INSTALL_GD=false
        - INSTALL_BCMATH=false
        - INSTALL_PHPREDIS=false
        - INSTALL_OPCACHE=false
        - INSTALL_IMAGEMAGICK=false
        - INSTALL_EXIF=false
        - INSTALL_PCNTL=true
        - INSTALL_INTL=false
        - INSTALL_SOAP=false
        - INSTALL_PGSQL=false
        - INSTALL_MYSQL=false
        - INSTALL_GETTEXT=false
        - INSTALL_SOCKETS=true
        - INSTALL_MEMCACHED=false
        - INSTALL_PECL_SYNC=false
    tty: true
    volumes:
      - ./../:/var/www/html:cached